package com.example.jakobsuell.spotd;

/**
 * This class is to hold all of the lists containing the pre-built word tag lists.
 * <p>
 * These are used to auto-complete and auto-suggest.
 */

public class WordTagLists {

    public String[] BasicColors = {
            "Black",
            "Blue",
            "Brown",
            "Chocolate",
            "Cream",
            "Gold",
            "Green",
            "Grey",
            "Orange",
            "Pink",
            "Red",
            "Silver",
            "Tan",
            "Violet",
            "White",
            "Yellow"
    };

    public String[] DogBreeds = {
            "Beagle",
            "Boxer",
            "Bulldog",
            "Chihuahua",
            "Chow Chow",
            "Collie",
            "Corgi",
            "Dachshund",
            "Dalmatian",
            "Dane",
            "Doberman",
            "Hound",
            "Husky",
            "Mastiff",
            "Pointer",
            "Poodle",
            "Pug",
            "Retriever",
            "Rottweiler",
            "Shepherd",
            "Terrier",
            "Spaniel",
            "Sheepdog",
            "Other"
    };

    public String[] CatBreeds = {
            "Abyssinian",
            "American Bobtail",
            "American Curl",
            "American Shorthair",
            "American Wirehair",
            "Balinese",
            "Bengal",
            "Birman",
            "Bombay",
            "British Shorthair",
            "Burmese",
            "Burmilla",
            "Chartreux",
            "Colorpoint Shorthair",
            "Cornish Rex",
            "Devon Rex",
            "Egyptian Mau",
            "European Burmese",
            "Exotic",
            "Havana Brown",
            "Japanese Bobtail",
            "Korat",
            "LaPerm",
            "Maine Coon",
            "Manx",
            "Norwegian Forest Cat",
            "Ocicat",
            "Oriental",
            "Persian",
            "Ragamuffin",
            "Ragdoll",
            "Russian Blue",
            "Scottish Fold",
            "Selkirk Rex",
            "Siamese",
            "Siberian",
            "Singapura",
            "Somali",
            "Sphynx",
            "Tonkinese",
            "Turkish Angora",
            "Turkish Van",
            "Other"
    };

    public String[] CatFurPatterns = {
            "Solid / Self-color",
            "Bi-color",
            "Tabby",
            "Tortoiseshell",
            "Tri-Color / Calico",
            "Color Point",
            "Other"
    };

    public String[] DogFurPatterns = {
            "Black and tan",
            "Liver and tan",
            "Blue and tan",
            "Bi-color",
            "Tri-color",
            "Merle",
            "Tuxedo",
            "Harlequin",
            "Spotted",
            "Flecked / Ticked / Speckled",
            "Brindle",
            "Saddle / Blanket",
            "Sable",
            "Other"
    };

    public String[] RabbitBreeds = {
            "American Fuzzy Lop",
            "Britannia Petite",
            "Dutch",
            "Dwarf Hotot",
            "Florida White",
            "Havana",
            "Himalayan",
            "Holland Lop",
            "Jersey Wolly",
            "Mini Lop",
            "Mini Rex",
            "Netherland Dwarf",
            "Polish",
            "Silver",
            "Tan",
            "American Sable",
            "Belgian Hare",
            "English angora",
            "English Spot",
            "French angora",
            "Harlequin",
            "Lilac",
            "Rex",
            "Rhinelander",
            "Satin Angora",
            "Silver Marten",
            "Standard Chinchilla",
            "American",
            "American Chinchilla",
            "Beveren",
            "Californian",
            "Champagne d'Argent",
            "Cinnamon",
            "Creme d'Argent",
            "English Lop",
            "Giant Angora",
            "Hotot",
            "New Zealand",
            "Palomino",
            "Satin",
            "Silver Fox",
            "Checkered Giant",
            "Continental Giant (Conti)",
            "Flemish Giant (Patagonian)",
            "French Lop",
            "Giant Chinchilla",
            "Other"
    };

    public String[] PigBreeds = {
            "Berkshire",
            "Chester White",
            "Duroc",
            "Hampshire",
            "Landrace",
            "Poland China",
            "Spotted",
            "Yorkshire",
            "Other"
    };

    public String[] BirdBreeds = {
            "American Golden Plover",
            "Arctic Tern",
            "Baleric Shearwater",
            "Barn Owl",
            "Barnacle Goose",
            "Bar-tailed Godwit",
            "Bean Goose",
            "Bewick's Swan",
            "Black Brant",
            "Black Guillemot",
            "Black Redstart",
            "Black Swan",
            "Blackbird",
            "Blackcap",
            "Black-headed Gull",
            "Black-necked Grebe",
            "Black-tailed Godwit",
            "Black-throated Diver",
            "Blue Tit",
            "Brambling",
            "Brent Goose (dark-bellied)",
            "Brent Goose (light-bellied)",
            "Buff-breasted Sandpiper",
            "Bullfinch",
            "Buzzard",
            "Canada Goose",
            "Chaffinch",
            "Chiffchaff",
            "Chough",
            "Coal Tit",
            "Collared Dove",
            "Common Gull",
            "Common Redpoll",
            "Common Sandpiper",
            "Common Scoter",
            "Common Tern",
            "Coot",
            "Cormorant ",
            "Corn Bunting",
            "Corncrake",
            "Cory's Shearwater",
            "Crossbill",
            "Cuckoo",
            "Curlew",
            "Curlew Sandpiper",
            "Dipper",
            "Dunlin",
            "Dunnock ",
            "Eider",
            "European White-fronted Goose ",
            "Feral pigeon",
            "Fieldfare",
            "Firecrest",
            "Fulmar ",
            "Gadwall",
            "Gannet ",
            "Garden Warbler",
            "Garganey",
            "Glaucous Gull",
            "Goldcrest",
            "Golden Eagle",
            "Golden Plover",
            "Goldeneye",
            "Goldfinch",
            "Goosander",
            "Goshawk",
            "Grasshopper Warbler",
            "Great Black-backed Gull",
            "Great Crested Grebe",
            "Great Northern Diver",
            "Great Skua",
            "Great Spotted Woodpecker",
            "Great Tit",
            "Green Sandpiper",
            "Greenfinch",
            "Greenland White-fronted Goose",
            "Greenshank",
            "Green-winged Teal",
            "Grey Heron",
            "Grey Partridge",
            "Grey Phalarope",
            "Grey Plover",
            "Grey Wagtail",
            "Greylag Goose ",
            "Guillemot ",
            "Hen Harrier",
            "Herring Gull",
            "Honey Buzzard",
            "Hooded Crow",
            "House Martin",
            "House Sparrow ",
            "Iceland Gull ",
            "Jack Snipe",
            "Jackdaw",
            "Jay ",
            "Kestrel",
            "Kingfisher",
            "Kittiwake",
            "Knot",
            "Lapwing",
            "Leach's Petrel",
            "Lesser Black-backed Gull",
            "Lesser Redpoll",
            "Lesser Whitethroat",
            "Linnet",
            "Little Egret",
            "Little Grebe",
            "Little Gull",
            "Little Ringed Plover",
            "Little Stint",
            "Little Tern",
            "Long-billed Dowitcher",
            "Long-eared Owl",
            "Long-tailed Duck",
            "Long-tailed Tit ",
            "Magpie",
            "Mallard",
            "Manx Shearwater",
            "Marsh Harrier",
            "Meadow Pipit",
            "Mediterranean Gull",
            "Merlin",
            "Mistle Thrush",
            "Moorhen",
            "Mute Swan ",
            "Nightjar ",
            "Oystercatcher ",
            "Pectoral Sandpiper",
            "Peregrine",
            "Pheasant",
            "Pied Flycatcher ",
            "Pied Wagtail",
            "Pink-footed Goose",
            "Pintail",
            "Pochard",
            "Puffin  ",
            "Purple Sandpiper ",
            "Quail ",
            "Raven",
            "Razorbill",
            "Red Grouse",
            "Red-breasted Merganser",
            "Red Kite",
            "Red-legged Partridge",
            "Red-necked Grebe",
            "Redshank",
            "Redstart",
            "Red-throated Diver",
            "Redwing",
            "Reed Bunting",
            "Reed Warbler",
            "Ring Ouzel",
            "Ring-billed Gull",
            "Ringed Plover",
            "Ring-necked Duck",
            "Robin",
            "Rock Dove",
            "Rock Pipit",
            "Rook",
            "Roseate Tern",
            "Ruddy Duck",
            "Ruff ",
            "Sabine's Gull",
            "Sand Martin",
            "Sanderling",
            "Sandwich Tern",
            "Scaup",
            "Sedge Warbler",
            "Shag",
            "Shelduck",
            "Short-eared Owl",
            "Shoveler",
            "Siskin",
            "Skylark",
            "Slavonian Grebe",
            "Smew",
            "Snipe",
            "Snow Bunting",
            "Snow Goose",
            "Snowy Owl",
            "Song Thrush",
            "Sparrowhawk",
            "Spotted Flycatcher",
            "Spotted Redshank",
            "Starling",
            "Stock Dove",
            "Stonechat",
            "Storm Petrel",
            "Surf Scoter",
            "Swallow",
            "Swift ",
            "Teal",
            "Tree Sparrow",
            "Treecreeper",
            "Tufted Duck",
            "Turnstone",
            "Turtle Dove",
            "Twite ",
            "Velvet Scoter",
            "Water Rail",
            "Waxwing",
            "Wheatear",
            "Whimbrel",
            "Whinchat",
            "White-tailed Sea Eagle",
            "Whitethroat",
            "Whooper Swan",
            "Wigeon",
            "Willow Warbler",
            "Wood Sandpiper",
            "Wood Warbler",
            "Woodcock",
            "Woodpigeon",
            "Wren ",
            "Yellow-browed Warbler",
            "Yellowhammer",
            "Other"
    };
}
